import Head from "next/head";
//Componensts Import Here
import Layout from "../components/Layout/Layout";

import HomeCarousel from "../components/Carsouel/HomeCarousel";
import HomePage from "./Home/HomePage";
export default function Home() {
  // const [token, setToken] = useState(null);
  // const [userId, setUserId] = useState(null);

  // AuthContext.login = (token, userId, tokenExpiration) => {
  //   setTimeout(() => setToken(token), 0);
  //   setTimeout(() => setUserId(userId), 0);
  // };

  // AuthContext.logout = () => {
  //   setToken(null);
  //   setUserId(null);
  // };

  return (
    <div>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Jupiterfull.png" />
      </Head>
      <HomePage/>
    </div>
  );
}